const audioPaths: { [key: string]: string } = {
    L1Words: '../assets/audio/L1 words.m4a',
    L2Words: '../assets/audio/L2 words.m4a',
    L3Words: '../assets/audio/L3 words.m4a',
    L4Words: '../assets/audio/L4 words.m4a',
    L5Words: '../assets/audio/L5 words.m4a',
    L6Words: '../assets/audio/L6 words.m4a',
    L7Words: '../assets/audio/L7 words.m4a',
    L8Words: '../assets/audio/L8 words.m4a',
    L9Words: '../assets/audio/L9 words.m4a',
    L10Words: '../assets/audio/L10 words.m4a',
    L11Words: '../assets/audio/L11 words.m4a',
    L12Words: '../assets/audio/L12 words.m4a',
    L13Words: '../assets/audio/L13 words.m4a',
    L14Words: '../assets/audio/L14 words.m4a',
    L15Words: '../assets/audio/L15 words.m4a',
    L16Words: '../assets/audio/L16 words.m4a',
    L17Words: '../assets/audio/L17 words.m4a',
    L19Words: '../assets/audio/L19 words.m4a',
    L20Words: '../assets/audio/L20 words.m4a',
    L21Words: '../assets/audio/L21 words.m4a',
    L5Text: '../assets/audio/L5 text.m4a',
    L9Text: '../assets/audio/L9 text.m4a',
    L10Text: '../assets/audio/L10 text.m4a',
    L11Text: '../assets/audio/L11 text.m4a',
    L12Text: '../assets/audio/L12 text.m4a',
    L13Text: '../assets/audio/L13 text.m4a',
    L14Text: '../assets/audio/L14 text.m4a',
    L15Text: '../assets/audio/L15 text.m4a',
    L16Text: '../assets/audio/L16 text.m4a',
    L17Text: '../assets/audio/L17 text.m4a',
    L18Text: '../assets/audio/L18 text.m4a',
    L19Text: '../assets/audio/L19 text.m4a',
    L20Text: '../assets/audio/L20 text.m4a',
    L21Text: '../assets/audio/L21 text.m4a',
};


    export default audioPaths;