import { AVPlaybackSource } from "expo-av";

const audioFiles: { [key: string]: AVPlaybackSource  } = {
    L1Words: require('../assets/audio/L1words.m4a'),
    L2Words: require('../assets/audio/L2words.m4a'),
    L3Words: require('../assets/audio/L3words.m4a'),
    L4Words: require('../assets/audio/L4words.m4a'),
    L5Words: require('../assets/audio/L5words.m4a'),
    L6Words: require('../assets/audio/L6words.m4a'),
    L7Words: require('../assets/audio/L7words.m4a'),
    L8Words: require('../assets/audio/L8words.m4a'),
    L9Words: require('../assets/audio/L9words.m4a'),
    L10Words: require('../assets/audio/L10words.m4a'),
    L11Words: require('../assets/audio/L11words.m4a'),
    L12Words: require('../assets/audio/L12words.m4a'),
    L13Words: require('../assets/audio/L13words.m4a'),
    L14Words: require('../assets/audio/L14words.m4a'),
    L15Words: require('../assets/audio/L15words.m4a'),
    L16Words: require('../assets/audio/L16words.m4a'),
    L17Words: require('../assets/audio/L17words.m4a'),
    L19Words: require('../assets/audio/L19words.m4a'),
    L20Words: require('../assets/audio/L20words.m4a'),
    L21Words: require('../assets/audio/L21words.m4a'),
    L5Text: require('../assets/audio/L5text.m4a'),
    L9Text: require('../assets/audio/L9text.m4a'),
    L10Text: require('../assets/audio/L10text.m4a'),
    L11Text: require('../assets/audio/L11text.m4a'),
    L12Text: require('../assets/audio/L12text.m4a'),
    L13Text: require('../assets/audio/L13text.m4a'),
    L14Text: require('../assets/audio/L14text.m4a'),
    L15Text: require('../assets/audio/L15text.m4a'),
    L16Text: require('../assets/audio/L16text.m4a'),
    L17Text: require('../assets/audio/L17text.m4a'),
    L18Text: require('../assets/audio/L18text.m4a'),
    L19Text: require('../assets/audio/L19text.m4a'),
    L20Text: require('../assets/audio/L20text.m4a'),
    L21Text: require('../assets/audio/L21text.m4a'),
  };
  
  export default audioFiles;
  